services:
  postgres:
    image: postgres:18-alpine
    container_name: postgres-db
    environment:
      POSTGRES_DB: razorpay-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d razorpayDB"]
      interval: 10s
      timeout: 5s
      retries: 3
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
  kafka:
    image: docker.io/confluentinc/confluent-local:7.5.8
    container_name: kafka-razorpay-db
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      # KRaft
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"

      # Listeners
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:29092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"

      # Controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:29093"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"

      # Single-node settings
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      CLUSTER_ID: 'orwcQc8MSHq0c6wqIU4eCA'

      # Topic defaults
      KAFKA_NUM_PARTITIONS: 3
    volumes:
      - kafka-data:/var/lib/kafka/data
    restart: unless-stopped
  control-center:
    image: confluentinc/cp-enterprise-control-center:7.5.8
    container_name: control-center-me
    depends_on:
      - kafka
    ports:
      - "9021:9021"
    environment:
      # -------------------------
      # Control Center
      # -------------------------
      CONTROL_CENTER_BOOTSTRAP_SERVERS: "kafka:9092"
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1

      CONTROL_CENTER_COMMAND_TOPIC_REPLICATION: 1
      CONTROL_CENTER_METRICS_TOPIC_REPLICATION: 1
      CONTROL_CENTER_STREAMS_NUM_STREAM_THREADS: 2

      # -------------------------
      # Control Center internal
      # -------------------------
      CONTROL_CENTER_ID: 1
      CONTROL_CENTER_REST_PORT: 9021
      CONTROL_CENTER_REST_ADVERTISED_HOST_NAME: control-center
      CONTROL_CENTER_CONNECT_CLUSTER:
      CONTROL_CENTER_KAFKA_CLUSTER_ID: 'orwcQc8MSHq0c6wqIU4eCA'
      CONTROL_CENTER_UI_LABEL: Razorpay Clone Kafka
    restart: unless-stopped
volumes:
  postgres_data:
  redis_data:
  kafka-data: